In [ ]:
!pip install pandas

In [2]:
import pandas as pd

In [10]:
df = pd.read_csv("C:\\Users\\amitm\\Downloads\\messy_sales_data.csv")

In [11]:
df.head()

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
0,ORD51058,CUST04879,Chaitanya Mane,bangalore,Grocery,net_banking,904.48,3.0,10,3.3,2023-04-24,29.0,chaitanya.mane@gmail.com,9454663439,Packaging was bad
1,ORD70248,CUST00177,Siddharth Sha,DELHI,SPORTS,Net Banking,1823.76,4.0,20,5.0,04-01-2023,38.0,NaN,NaN,great service
2,ORD43804,CUST04537,Nathaniel Chatterjee,chennai,electronic,Upi,770.67,1.0,0,4.9,11/17/2024,40.0,nathaniel.chatterjee@outlook.com,9573975601,Okayish product
3,ORD46367,CUST07605,pranit contractor,Jaipur,Clothing,COD,2028.06,1.0,0,2.9,NaN,41.0,pranit.contractor@rediffmail.com,9235766629,NaN
4,ORD32922,CUST03180,Hemang Chakraborty,Amdavad,FURNITURE,cc,604.00,4.0,10,3.7,14 Jan 2023,44.0,hemang.chakraborty@outlook.com,9731250657,Superb!!! fast delivery

In [12]:
df.tail()

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
106570,ORD49057,CUST01636,MAX OM,chennai,FURNITURE,debit card,Rs.1961.37,4.0,0,5.0,2023-06-11,32.0,max.om@outlook.com,9123457578,Amazing quality!!!
106571,ORD60012,CUST01826,CHARAN MANNE,pune,Toys,Cash on Delivery,Rs.1468.22,2.0,20,3.3,22 Apr 2024,43.0,charan.manne@yahoo.com,9226831132,Good product loved it
106572,ORD78050,CUST04033,Isaiah Wali,DELHI,Furniture,Debit Card,414.94,2.0,10,3.3,11/09/2024,23.0,isaiah.wali@hotmail.com,9758098090,Not satisfied poor quality
106573,ORD68225,CUST04602,Ladli Nazareth,AHMEDABAD,electronic,DEBIT CARD,916.52,1.0,25,4.6,19/12/2024,50.0,NaN,9914721436,NaN
106574,ORD72531,CUST07969,Yatin Rao,Chennai,Sport,DEBIT CARD,891.46,2.0,5,4.3,2024-09-29,32.0,yatin.rao@gmail.com,9438589142,Superb!!! fast delivery

In [13]:
df.shape

(106575, 15)

In [14]:
df.size

1598625

In [15]:
df.columns

Index(['OrderID', 'CustomerID', 'CustomerName', 'City', 'Category',
       'PaymentMode', 'Price', 'Quantity', 'DiscountPct', 'Rating',
       'OrderDate', 'CustomerAge', 'Email', 'Phone', 'ReviewText'],
      dtype='str')

In [17]:
df.dtypes

OrderID             str
CustomerID          str
CustomerName        str
City                str
Category            str
PaymentMode         str
Price               str
Quantity        float64
DiscountPct       int64
Rating          float64
OrderDate           str
CustomerAge     float64
Email               str
Phone               str
ReviewText          str
dtype: object

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 106575 entries, 0 to 106574
Data columns (total 15 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   OrderID       106575 non-null  str
 1   CustomerID    106575 non-null  str
 2   CustomerName  106575 non-null  str
 3   City          104481 non-null  str
 4   Category      106575 non-null  str
 5   PaymentMode   103332 non-null  str
 6   Price         106575 non-null  str
 7   Quantity      106575 non-null  float64
 8   DiscountPct   106575 non-null  int64
 9   Rating        100129 non-null  float64
 10  OrderDate     102358 non-null  str
 11  CustomerAge   106575 non-null  float64
 12  Email         99176 non-null   str
 13  Phone         98117 non-null   str
 14  ReviewText    93200 non-null   str
dtypes: float64(3), int64(1), str(11)
memory usage: 12.2 MB

In [20]:
df.isnull().sum()

OrderID             0
CustomerID          0
CustomerName        0
City             2094
Category            0
PaymentMode      3243
Price               0
Quantity            0
DiscountPct         0
Rating           6446
OrderDate        4217
CustomerAge         0
Email            7399
Phone            8458
ReviewText      13375
dtype: int64

In [22]:
df.isna().sum()

OrderID             0
CustomerID          0
CustomerName        0
City             2094
Category            0
PaymentMode      3243
Price               0
Quantity            0
DiscountPct         0
Rating           6446
OrderDate        4217
CustomerAge         0
Email            7399
Phone            8458
ReviewText      13375
dtype: int64

In [23]:
df.isnull().sum().sum()

np.int64(45232)

In [26]:
df.describe()

            Quantity    DiscountPct         Rating    CustomerAge
count  106575.000000  106575.000000  100129.000000  106575.000000
mean        2.066817       9.382125       3.409874      39.678893
std         1.387769       9.176865       1.306731      19.263288
min        -5.000000       0.000000       0.500000       0.000000
25%         1.000000       0.000000       2.600000      28.000000
50%         2.000000      10.000000       3.300000      38.000000
75%         3.000000      20.000000       4.100000      47.000000
max         5.000000      25.000000       9.900000     150.000000

In [30]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
OrderID,106575,105000,ORD72254,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CustomerID,106575,9000,CUST01057,27,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CustomerName,106575,37440,Charvi Dara,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
City,104481,56,hyderabad,2652,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category,106575,35,BEAUTY,4499,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PaymentMode,103332,24,cash on delivery,5184,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Price,106575,88579,966.86,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Quantity,106575.0,NaN,NaN,NaN,2.066817,1.387769,-5.0,1.0,2.0,3.0,5.0
DiscountPct,106575.0,NaN,NaN,NaN,9.382125,9.176865,0.0,0.0,10.0,20.0,25.0
Rating,100129.0,NaN,NaN,NaN,3.409874,1.306731,0.5,2.6,3.3,4.1,9.9
OrderDate,102358,3367,01/03/2024,82,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CustomerAge,106575.0,NaN,NaN,NaN,39.678893,19.263288,0.0,28.0,38.0,47.0,150.0
Email,99176,39350,chakradhar.venkataraman@rediffmail.com,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Phone,98117,96653,9783418336,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ReviewText,93200,14,worst product ever received damaged item,6785,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
type(df.City)

pandas.Series

In [37]:
df.City

0         bangalore
1             DELHI
2           chennai
3           Jaipur
4           Amdavad
            ...
106570      chennai
106571         pune
106572        DELHI
106573    AHMEDABAD
106574      Chennai
Name: City, Length: 106575, dtype: str

In [44]:
type(df[["City", "Price", "Category"]])

pandas.DataFrame

In [43]:
df[["City", "Price", "Category"]]

             City       Price    Category
0       bangalore      904.48     Grocery
1           DELHI     1823.76      SPORTS
2         chennai      770.67  electronic
3         Jaipur      2028.06    Clothing
4         Amdavad      604.00   FURNITURE
...           ...         ...         ...
106570    chennai  Rs.1961.37   FURNITURE
106571       pune  Rs.1468.22        Toys
106572      DELHI      414.94   Furniture
106573  AHMEDABAD      916.52  electronic
106574    Chennai      891.46       Sport

[106575 rows x 3 columns]

In [45]:
df["City"].value_counts()

City
hyderabad     2652
Jaipur        2651
JAIPUR        2635
LUCKNOW       2634
Jaipur        2631
 Hyderabad    2628
 Lucknow      2602
Hyderabad     2585
Lucknow       2575
jaipur        2569
HYDERABAD     2562
lucknow       2547
Ahmedabad     2134
Poona         2129
pune          2124
Amdavad       2110
Pune          2093
PUNE          2086
ahmedabad     2085
amdavad       2082
poona         2012
AHMEDABAD     1994
CALCUTTA      1833
madras        1816
Madras        1807
chennai       1805
Calcutta      1792
Chennai       1791
Kolkata       1755
KOLKATA       1753
kolkata       1739
CHENNAI       1728
calcutta      1672
MADRAS        1663
banglore      1557
bangalore     1549
New Delhi     1526
NEW DELHI     1517
Bangalore     1517
bengaluru     1488
BANGALORE     1481
new delhi     1473
Bengaluru     1462
DELHI         1456
delhi         1448
Delhi         1444
Banglore      1436
 Delhi        1396
BOMBAY        1362
Mumbai        1339
mumbai        1315
 Mumbai       1300
bombay        1298
mumbai        1296
MUMBAI        1281
Bombay        1266
Name: count, dtype: int64

In [47]:
df["Category"].nunique()

35

In [48]:
df["Category"].unique()

<StringArray>
[    'Grocery',      'SPORTS',  'electronic',    'Clothing',   'FURNITURE',
    'CLOTHING',      'BEAUTY',  'Furnitures',   'Clothings', 'electronics',
      'Beauty',        'TOYS',      'sports',      'beauty',     'grocery',
        'Book',      'Sports',   'Groceries', 'Electronics',        'book',
       'Books',     'GROCERY',   'Clothing ',       'books',   'furniture',
 'ELECTRONICS',   'Furniture',    'clothing',        'Toys',  'Electronic',
        'toys',         'Toy',       'BOOKS',         'toy',       'Sport']
Length: 35, dtype: str

In [49]:
df["Category"].value_counts()

Category
BEAUTY         4499
Beauty         4429
beauty         4380
furniture      3464
SPORTS         3401
sports         3345
GROCERY        3331
FURNITURE      3314
Furnitures     3312
Grocery        3307
Furniture      3303
grocery        3299
Sports         3294
Groceries      3268
Sport          3250
electronic     2806
toys           2802
Toy            2747
CLOTHING       2723
ELECTRONICS    2712
Clothings      2695
Clothing       2695
Book           2684
BOOKS          2671
Clothing       2670
clothing       2657
books          2656
book           2655
Electronic     2654
TOYS           2646
toy            2622
Books          2590
Electronics    2588
electronics    2565
Toys           2541
Name: count, dtype: int64

In [51]:
df.duplicated().sum()

np.int64(1056)

In [52]:
df.head()

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
0,ORD51058,CUST04879,Chaitanya Mane,bangalore,Grocery,net_banking,904.48,3.0,10,3.3,2023-04-24,29.0,chaitanya.mane@gmail.com,9454663439,Packaging was bad
1,ORD70248,CUST00177,Siddharth Sha,DELHI,SPORTS,Net Banking,1823.76,4.0,20,5.0,04-01-2023,38.0,NaN,NaN,great service
2,ORD43804,CUST04537,Nathaniel Chatterjee,chennai,electronic,Upi,770.67,1.0,0,4.9,11/17/2024,40.0,nathaniel.chatterjee@outlook.com,9573975601,Okayish product
3,ORD46367,CUST07605,pranit contractor,Jaipur,Clothing,COD,2028.06,1.0,0,2.9,NaN,41.0,pranit.contractor@rediffmail.com,9235766629,NaN
4,ORD32922,CUST03180,Hemang Chakraborty,Amdavad,FURNITURE,cc,604.00,4.0,10,3.7,14 Jan 2023,44.0,hemang.chakraborty@outlook.com,9731250657,Superb!!! fast delivery

In [56]:
df["total_sales"] = df['Rating']*df["Quantity"]

In [57]:
df.dtypes

OrderID             str
CustomerID          str
CustomerName        str
City                str
Category            str
PaymentMode         str
Price               str
Quantity        float64
DiscountPct       int64
Rating          float64
OrderDate           str
CustomerAge     float64
Email               str
Phone               str
ReviewText          str
total_sales     float64
dtype: object

In [58]:
df["col1"] = df["PaymentMode"]

In [60]:
df.head()

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText,total_sales,col1
0,ORD51058,CUST04879,Chaitanya Mane,bangalore,Grocery,net_banking,904.48,3.0,10,3.3,2023-04-24,29.0,chaitanya.mane@gmail.com,9454663439,Packaging was bad,9.9,net_banking
1,ORD70248,CUST00177,Siddharth Sha,DELHI,SPORTS,Net Banking,1823.76,4.0,20,5.0,04-01-2023,38.0,NaN,NaN,great service,20.0,Net Banking
2,ORD43804,CUST04537,Nathaniel Chatterjee,chennai,electronic,Upi,770.67,1.0,0,4.9,11/17/2024,40.0,nathaniel.chatterjee@outlook.com,9573975601,Okayish product,4.9,Upi
3,ORD46367,CUST07605,pranit contractor,Jaipur,Clothing,COD,2028.06,1.0,0,2.9,NaN,41.0,pranit.contractor@rediffmail.com,9235766629,NaN,2.9,COD
4,ORD32922,CUST03180,Hemang Chakraborty,Amdavad,FURNITURE,cc,604.00,4.0,10,3.7,14 Jan 2023,44.0,hemang.chakraborty@outlook.com,9731250657,Superb!!! fast delivery,14.8,cc

In [63]:
df.sample(5)

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText,total_sales,col1
73894,ORD16235,CUST04008,Xavier Dyal,Mumbai,books,Debit Card,1550.56,2.0,20,4.5,09/19/2024,29.0,xavier.dyal@rediffmail.com,9761656740,value for money,9.0,Debit Card
50683,ORD58512,CUST06714,Saksham Shan,KOLKATA,sports,cod,1136.05,3.0,5,2.4,2024-12-28,41.0,saksham.shan@hotmail.com,9775251080,Will not recommend,7.2,cod
94947,ORD95416,CUST04598,AVI RAI,Madras,clothing,cod,942.03,3.0,0,2.6,04/18/2024,54.0,avi.rai@hotmail.com,9368906904,Superb!!! fast delivery,7.8,cod
36764,ORD33763,CUST06101,Karan Dhillon,pune,Furnitures,cash on delivery,443.74,2.0,20,4.7,04 Aug 2023,30.0,karan.dhillon@yahoo.com,NaN,Superb!!! fast delivery,9.4,cash on delivery
79719,ORD66598,CUST01205,KRITIKA RAU,amdavad,Sport,NaN,1652.98,2.0,15,5.0,24-03-2023,38.0,kritika.rau@rediffmail.com,9788999847,Not satisfied poor quality,10.0,NaN

In [67]:
df.drop("col1", axis = 1)

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText,total_sales
0,ORD51058,CUST04879,Chaitanya Mane,bangalore,Grocery,net_banking,904.48,3.0,10,3.3,2023-04-24,29.0,chaitanya.mane@gmail.com,9454663439,Packaging was bad,9.9
1,ORD70248,CUST00177,Siddharth Sha,DELHI,SPORTS,Net Banking,1823.76,4.0,20,5.0,04-01-2023,38.0,NaN,NaN,great service,20.0
2,ORD43804,CUST04537,Nathaniel Chatterjee,chennai,electronic,Upi,770.67,1.0,0,4.9,11/17/2024,40.0,nathaniel.chatterjee@outlook.com,9573975601,Okayish product,4.9
3,ORD46367,CUST07605,pranit contractor,Jaipur,Clothing,COD,2028.06,1.0,0,2.9,NaN,41.0,pranit.contractor@rediffmail.com,9235766629,NaN,2.9
4,ORD32922,CUST03180,Hemang Chakraborty,Amdavad,FURNITURE,cc,604.00,4.0,10,3.7,14 Jan 2023,44.0,hemang.chakraborty@outlook.com,9731250657,Superb!!! fast delivery,14.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106570,ORD49057,CUST01636,MAX OM,chennai,FURNITURE,debit card,Rs.1961.37,4.0,0,5.0,2023-06-11,32.0,max.om@outlook.com,9123457578,Amazing quality!!!,20.0
106571,ORD60012,CUST01826,CHARAN MANNE,pune,Toys,Cash on Delivery,Rs.1468.22,2.0,20,3.3,22 Apr 2024,43.0,charan.manne@yahoo.com,9226831132,Good product loved it,6.6
106572,ORD78050,CUST04033,Isaiah Wali,DELHI,Furniture,Debit Card,414.94,2.0,10,3.3,11/09/2024,23.0,isaiah.wali@hotmail.com,9758098090,Not satisfied poor quality,6.6
106573,ORD68225,CUST04602,Ladli Nazareth,AHMEDABAD,electronic,DEBIT CARD,916.52,1.0,25,4.6,19/12/2024,50.0,NaN,9914721436,NaN,4.6
106574,ORD72531,CUST07969,Yatin Rao,Chennai,Sport,DEBIT CARD,891.46,2.0,5,4.3,2024-09-29,32.0,yatin.rao@gmail.com,9438589142,Superb!!! fast delivery,8.6

In [68]:
df.head()

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText,total_sales,col1
0,ORD51058,CUST04879,Chaitanya Mane,bangalore,Grocery,net_banking,904.48,3.0,10,3.3,2023-04-24,29.0,chaitanya.mane@gmail.com,9454663439,Packaging was bad,9.9,net_banking
1,ORD70248,CUST00177,Siddharth Sha,DELHI,SPORTS,Net Banking,1823.76,4.0,20,5.0,04-01-2023,38.0,NaN,NaN,great service,20.0,Net Banking
2,ORD43804,CUST04537,Nathaniel Chatterjee,chennai,electronic,Upi,770.67,1.0,0,4.9,11/17/2024,40.0,nathaniel.chatterjee@outlook.com,9573975601,Okayish product,4.9,Upi
3,ORD46367,CUST07605,pranit contractor,Jaipur,Clothing,COD,2028.06,1.0,0,2.9,NaN,41.0,pranit.contractor@rediffmail.com,9235766629,NaN,2.9,COD
4,ORD32922,CUST03180,Hemang Chakraborty,Amdavad,FURNITURE,cc,604.00,4.0,10,3.7,14 Jan 2023,44.0,hemang.chakraborty@outlook.com,9731250657,Superb!!! fast delivery,14.8,cc

In [69]:
df1 = df.drop("col1", axis = 1)

In [70]:
df1.head()

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText,total_sales
0,ORD51058,CUST04879,Chaitanya Mane,bangalore,Grocery,net_banking,904.48,3.0,10,3.3,2023-04-24,29.0,chaitanya.mane@gmail.com,9454663439,Packaging was bad,9.9
1,ORD70248,CUST00177,Siddharth Sha,DELHI,SPORTS,Net Banking,1823.76,4.0,20,5.0,04-01-2023,38.0,NaN,NaN,great service,20.0
2,ORD43804,CUST04537,Nathaniel Chatterjee,chennai,electronic,Upi,770.67,1.0,0,4.9,11/17/2024,40.0,nathaniel.chatterjee@outlook.com,9573975601,Okayish product,4.9
3,ORD46367,CUST07605,pranit contractor,Jaipur,Clothing,COD,2028.06,1.0,0,2.9,NaN,41.0,pranit.contractor@rediffmail.com,9235766629,NaN,2.9
4,ORD32922,CUST03180,Hemang Chakraborty,Amdavad,FURNITURE,cc,604.00,4.0,10,3.7,14 Jan 2023,44.0,hemang.chakraborty@outlook.com,9731250657,Superb!!! fast delivery,14.8

In [71]:
df.head()

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText,total_sales,col1
0,ORD51058,CUST04879,Chaitanya Mane,bangalore,Grocery,net_banking,904.48,3.0,10,3.3,2023-04-24,29.0,chaitanya.mane@gmail.com,9454663439,Packaging was bad,9.9,net_banking
1,ORD70248,CUST00177,Siddharth Sha,DELHI,SPORTS,Net Banking,1823.76,4.0,20,5.0,04-01-2023,38.0,NaN,NaN,great service,20.0,Net Banking
2,ORD43804,CUST04537,Nathaniel Chatterjee,chennai,electronic,Upi,770.67,1.0,0,4.9,11/17/2024,40.0,nathaniel.chatterjee@outlook.com,9573975601,Okayish product,4.9,Upi
3,ORD46367,CUST07605,pranit contractor,Jaipur,Clothing,COD,2028.06,1.0,0,2.9,NaN,41.0,pranit.contractor@rediffmail.com,9235766629,NaN,2.9,COD
4,ORD32922,CUST03180,Hemang Chakraborty,Amdavad,FURNITURE,cc,604.00,4.0,10,3.7,14 Jan 2023,44.0,hemang.chakraborty@outlook.com,9731250657,Superb!!! fast delivery,14.8,cc

In [73]:
df.drop("col1", axis = 1, inplace=True)

KeyError: "['col1'] not found in axis"

In [ ]:
df.hrad