## variable

In [1]:
a = 10

In [2]:
1a = 10

SyntaxError: invalid decimal literal (482919702.py, line 1)

In [3]:
last name = "amit"

SyntaxError: invalid syntax (2520428723.py, line 1)

In [4]:
last_name = "AMIT"

In [5]:
last_name

'AMIT'

In [7]:
a, b, c = 40, 30, 20

In [8]:
a

40

In [9]:
b

30

In [10]:
c

20

## datatypes

In [ ]:
int 
float
complex = 34 + 7j
bool
str =  ' ' " "

## data structure

In [ ]:
list = []
tuple = ()
set = {}
dict = {"k":"v"}

In [13]:
print("hello")
print("world")
print(3/0)
print("python")

hello
world

ZeroDivisionError: division by zero

In [15]:
print("hello")
print("world")
try:
    print(3/0)
except Exception as e:
    print(e)
print("python")

hello
world
division by zero
python

In [18]:
try:
    age = int(input("Enter your age: "))
    print("Your age is:", age)

except ValueError:
    print("Please enter a valid number")
except Exception as e:
    print(e)

Enter your age:  []

Please enter a valid number

In [19]:
try:
    file = open("abc.txt", "r")
    print(file.read())

except FileNotFoundError:
    print("File not found")

File not found

In [20]:
file = open("abc.txt", "r")
print(file.read())

FileNotFoundError: [Errno 2] No such file or directory: 'abc.txt'

In [22]:
import logging

In [23]:
import math

In [24]:
math.comb(8, 3)

56

In [25]:
math.sqrt(76)

8.717797887081348

In [26]:
math.factorial(7)

5040

In [27]:
import random

In [30]:
random.random()

0.34235010398259935

In [35]:
random.randint(2, 9)

6

In [36]:
math.pi

3.141592653589793

In [37]:
math.tau

6.283185307179586

In [38]:
math.e

2.718281828459045

## OOPs

In [ ]:
class
self
__init__
method
attributes
public
protected
private
inheritence
encapsulation
polymorphism

In [45]:
class Car:

    def __init__(self, brand, model, color, price, year, fuel_type, engine, mileage):
        self.brand = brand
        self.model = model
        self.color = color
        self.price = price
        self.year = year
        self.fuel_type = fuel_type
        self.engine = engine
        self.mileage = mileage

    def show_details(self):
        print("Car Brand   :", self.brand)
        print("Car Model   :", self.model)
        print("Color       :", self.color)
        print("Price       :", self.price)
        print("Year        :", self.year)
        print("Fuel Type   :", self.fuel_type)
        print("Engine      :", self.engine)
        print("Mileage     :", self.mileage)

    def start(self):
        print(self.brand, self.model, "is started.")

    def stop(self):
        print(self.brand, self.model, "is stopped.")

    def drive(self):
        print(self.brand, self.model, "is running on the road.")

In [46]:
obj1 = Car( "Toyota",
    "Fortuner",
    "White",
    4000000,
    2025,
    "Diesel",
    "2.8L",
    "14 km/l")

In [47]:
obj2 = Car(
    "Hyundai",
    "Creta",
    "Black",
    1800000,
    2024,
    "Petrol",
    "1.5L",
    "17 km/l"
)

In [48]:
obj3 = Car(
    "Honda",
    "amaze",
    "Black",
    800000,
    2026,
    "Petrol",
    "1.2L",
    "17 km/l"
)

In [49]:
obj1.mileage

'14 km/l'

In [50]:
obj1.show_details()

Car Brand   : Toyota
Car Model   : Fortuner
Color       : White
Price       : 4000000
Year        : 2025
Fuel Type   : Diesel
Engine      : 2.8L
Mileage     : 14 km/l

In [51]:
obj2.show_details()

Car Brand   : Hyundai
Car Model   : Creta
Color       : Black
Price       : 1800000
Year        : 2024
Fuel Type   : Petrol
Engine      : 1.5L
Mileage     : 17 km/l

In [52]:
obj2.drive()

Hyundai Creta is running on the road.

In [54]:
class Car:

    def __init__(self, brand, model, color, price):
        self.brand = brand
        self.model = model
        self.color = color
        self.price = price

    def start(self):
        print(self.brand, "is started.")

    def stop(self):
        print(self.brand, "is stopped.")

    def show_details(self):
        print("Brand :", self.brand)
        print("Model :", self.model)
        print("Color :", self.color)
        print("Price :", self.price)

In [55]:
class ElectricCar(Car):

    def charge_battery(self):
        print(self.brand, "battery is charging.")

In [57]:
car1 = ElectricCar(
    "Tesla",
    "Model 3",
    "White",
    4500000
)

In [58]:
car1.model

'Model 3'

In [59]:
car1.show_details()

Brand : Tesla
Model : Model 3
Color : White
Price : 4500000

In [60]:
car1.charge_battery()

Tesla battery is charging.

In [61]:
class BankAccount:

    def __init__(self, name, balance):
        self.name = name
        self.__balance = balance

    def show_balance(self):
        print("Balance:", self.__balance)

    def deposit(self, amount):
        if amount > 0:
            self.__balance += amount
            print("Amount deposited:", amount)
        else:
            print("Invalid amount")

    def withdraw(self, amount):
        if amount <= self.__balance:
            self.__balance -= amount
            print("Amount withdrawn:", amount)
        else:
            print("Insufficient balance")

In [62]:
bank = BankAccount("amit", 60000)

In [63]:
bank.name

'amit'

In [64]:
bank.show_balance()

Balance: 60000

In [65]:
bank.deposit(50000)

Amount deposited: 50000

In [66]:
bank.show_balance()

Balance: 110000

In [67]:
bank.withdraw(70000)

Amount withdrawn: 70000

In [68]:
bank.show_balance()

Balance: 40000

In [69]:
class Car:

    def start(self):
        print("Car is starting")

    def stop(self):
        print("Car is stopping")

    def drive(self):
        print("Car is driving")


class ElectricCar(Car):

    def start(self):
        print("Electric car starts with a button")

    def drive(self):
        print("Electric car is driving silently")


class SportsCar(Car):

    def start(self):
        print("Sports car starts very quickly")

    def drive(self):
        print("Sports car is driving very fast")

In [71]:
car1 = Car()
car2 = ElectricCar()
car3 = SportsCar()

In [72]:
cars = [car1, car2, car3]

In [73]:
for i in cars:
    i.start()
    i.drive()
    i.stop()

Car is starting
Car is driving
Car is stopping
Electric car starts with a button
Electric car is driving silently
Car is stopping
Sports car starts very quickly
Sports car is driving very fast
Car is stopping

In [74]:
def startt(obj):
    obj.start()

In [77]:
startt(car3)

Sports car starts very quickly

In [78]:
def square(x):
    return x * x

In [79]:
print(square(5))

25

In [81]:
fun1 = lambda x : x*x

In [82]:
fun1(8)

64

In [83]:
std1 = [70, 66, 80, 44, 85]

In [86]:
(sum(std1)/500)*100

69.0

In [87]:
def perc(s1, s2, s3, s4, s5):
    s_sum = s1+s2+s3+s4+s5
    pec = (s_sum/500  )*100
    return pec

In [89]:
perc(78, 90, 44, 56, 77)

69.0

In [91]:
p_fun = lambda marks : (marks/500)*100

In [93]:
p_fun(320)

64.0

In [98]:
fun2 = lambda s1, s2, s3, s4, s5 : round(((s1+s2+s3+s4+s5)/500)*100, 2)

In [99]:
fun2(78, 88, 92, 86, 59)

80.6

In [100]:
import pandas as pd

In [102]:
df = pd.read_csv("https://raw.githubusercontent.com/Amitmakode/X-DSAAI-15/refs/heads/main/Python/22.%20messy_sales_data.csv?token=GHSAT0AAAAAADN6CAG3ONCBHI752WAVTH7U2US5A7A")

In [103]:
data = df.copy()

In [104]:
data.head()

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
0,ORD51058,CUST04879,Chaitanya Mane,bangalore,Grocery,net_banking,904.48,3.0,10,3.3,2023-04-24,29.0,chaitanya.mane@gmail.com,9454663439,Packaging was bad
1,ORD70248,CUST00177,Siddharth Sha,DELHI,SPORTS,Net Banking,1823.76,4.0,20,5.0,04-01-2023,38.0,NaN,NaN,great service
2,ORD43804,CUST04537,Nathaniel Chatterjee,chennai,electronic,Upi,770.67,1.0,0,4.9,11/17/2024,40.0,nathaniel.chatterjee@outlook.com,9573975601,Okayish product
3,ORD46367,CUST07605,pranit contractor,Jaipur,Clothing,COD,2028.06,1.0,0,2.9,NaN,41.0,pranit.contractor@rediffmail.com,9235766629,NaN
4,ORD32922,CUST03180,Hemang Chakraborty,Amdavad,FURNITURE,cc,604.00,4.0,10,3.7,14 Jan 2023,44.0,hemang.chakraborty@outlook.com,9731250657,Superb!!! fast delivery

In [105]:
data.tail()

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
106570,ORD49057,CUST01636,MAX OM,chennai,FURNITURE,debit card,Rs.1961.37,4.0,0,5.0,2023-06-11,32.0,max.om@outlook.com,9123457578,Amazing quality!!!
106571,ORD60012,CUST01826,CHARAN MANNE,pune,Toys,Cash on Delivery,Rs.1468.22,2.0,20,3.3,22 Apr 2024,43.0,charan.manne@yahoo.com,9226831132,Good product loved it
106572,ORD78050,CUST04033,Isaiah Wali,DELHI,Furniture,Debit Card,414.94,2.0,10,3.3,11/09/2024,23.0,isaiah.wali@hotmail.com,9758098090,Not satisfied poor quality
106573,ORD68225,CUST04602,Ladli Nazareth,AHMEDABAD,electronic,DEBIT CARD,916.52,1.0,25,4.6,19/12/2024,50.0,NaN,9914721436,NaN
106574,ORD72531,CUST07969,Yatin Rao,Chennai,Sport,DEBIT CARD,891.46,2.0,5,4.3,2024-09-29,32.0,yatin.rao@gmail.com,9438589142,Superb!!! fast delivery

In [106]:
data.sample(5)

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
84785,ORD71663,CUST05272,RACHIT BORDE,MADRAS,Sport,net_banking,1069.95,1.0,20,3.5,05/07/2024,71.0,rachit.borde@hotmail.com,9531969666,Average experience
29597,ORD29786,CUST04286,Odika Purohit,Hyderabad,toy,net_banking,482.49,1.0,0,3.5,20-09-2023,40.0,odika.purohit@yahoo.com,9660409468,delivery was late
40878,ORD81341,CUST03032,Yagnesh Bhalla,HYDERABAD,Book,credit card,1258.59,1.0,20,NaN,12/12/2023,29.0,NaN,9348657836,delivery was late
33789,ORD94465,CUST07326,Yoshita Prabhu,Bangalore,toys,DC,400.81,1.0,20,4.6,2023-06-29,47.0,yoshita.prabhu@yahoo.com,9962115969,Average experience
98656,ORD36421,CUST04262,Brinda Sandhu,Bengaluru,Toys,net_banking,1805.79,2.0,25,2.2,2023-04-14,34.0,brinda.sandhu@yahoo.com,NaN,Not satisfied poor quality

In [107]:
data.index

RangeIndex(start=0, stop=106575, step=1)

In [109]:
len(data.columns)

15

In [113]:
data.columns

Index(['OrderID', 'CustomerID', 'CustomerName', 'City', 'Category',
       'PaymentMode', 'Price', 'Quantity', 'DiscountPct', 'Rating',
       'OrderDate', 'CustomerAge', 'Email', 'Phone', 'ReviewText'],
      dtype='str')

In [114]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 106575 entries, 0 to 106574
Data columns (total 15 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   OrderID       106575 non-null  str
 1   CustomerID    106575 non-null  str
 2   CustomerName  106575 non-null  str
 3   City          104481 non-null  str
 4   Category      106575 non-null  str
 5   PaymentMode   103332 non-null  str
 6   Price         106575 non-null  str
 7   Quantity      106575 non-null  float64
 8   DiscountPct   106575 non-null  int64
 9   Rating        100129 non-null  float64
 10  OrderDate     102358 non-null  str
 11  CustomerAge   106575 non-null  float64
 12  Email         99176 non-null   str
 13  Phone         98117 non-null   str
 14  ReviewText    93200 non-null   str
dtypes: float64(3), int64(1), str(11)
memory usage: 12.2 MB

In [115]:
data.dtypes

OrderID             str
CustomerID          str
CustomerName        str
City                str
Category            str
PaymentMode         str
Price               str
Quantity        float64
DiscountPct       int64
Rating          float64
OrderDate           str
CustomerAge     float64
Email               str
Phone               str
ReviewText          str
dtype: object

In [117]:
type(data.Email)

pandas.Series

In [120]:
type(data[["Email", "Price"]])

pandas.DataFrame

In [125]:
data.loc[0:200:10, "OrderID":"Price":2]

       OrderID       CustomerName     Category       Price
0     ORD51058     Chaitanya Mane      Grocery      904.48
10    ORD93895     ZILMIL PRADHAN   Furnitures     1605.42
20    ORD97886  Laban Swaminathan         Book      974.21
30    ORD16114       TANVEER NAGI    FURNITURE   Rs.425.32
40    ORD75984       Abhiram Kaul     CLOTHING   ₹1,512.29
50   ORD105339       Liam Patla      Clothings  Rs.1056.12
60    ORD21029       balendra tak     CLOTHING   ₹2,110.56
70    ORD16360     Isaiah Sachdev    Furniture     1617.19
80     ORD1372    priya chaudhuri    Clothing      -970.72
90    ORD78760        Jyoti Lanka  electronics     1308.21
100   ORD52933        Watika Peri       BEAUTY     1093.11
110   ORD20288        BALVEER RAM        Books      344.35
120   ORD48424    NIHARIKA MUNSHI  ELECTRONICS     1117.33
130   ORD42875       Arjun Shukla         toys      953.44
140   ORD92712       Girik Khalsa    Groceries      969.07
150   ORD42630     Udarsh Dugar         Beauty      398.71
160   ORD38852    Vihaan Aggarwal     clothing     -534.68
170   ORD86928        avi iyengar      GROCERY      764.75
180   ORD69030    Prisha Dhaliwal        books     1515.65
190   ORD78882      David Krishna      GROCERY   ₹1,748.83
200   ORD89971    omisha tailor         sports      645.33

In [126]:
data.iloc[0:200:10, 0:10:2]

       OrderID       CustomerName     Category       Price  DiscountPct
0     ORD51058     Chaitanya Mane      Grocery      904.48           10
10    ORD93895     ZILMIL PRADHAN   Furnitures     1605.42            5
20    ORD97886  Laban Swaminathan         Book      974.21           25
30    ORD16114       TANVEER NAGI    FURNITURE   Rs.425.32           10
40    ORD75984       Abhiram Kaul     CLOTHING   ₹1,512.29            0
50   ORD105339       Liam Patla      Clothings  Rs.1056.12           20
60    ORD21029       balendra tak     CLOTHING   ₹2,110.56           25
70    ORD16360     Isaiah Sachdev    Furniture     1617.19           15
80     ORD1372    priya chaudhuri    Clothing      -970.72            0
90    ORD78760        Jyoti Lanka  electronics     1308.21           15
100   ORD52933        Watika Peri       BEAUTY     1093.11           15
110   ORD20288        BALVEER RAM        Books      344.35            0
120   ORD48424    NIHARIKA MUNSHI  ELECTRONICS     1117.33            0
130   ORD42875       Arjun Shukla         toys      953.44           25
140   ORD92712       Girik Khalsa    Groceries      969.07           10
150   ORD42630     Udarsh Dugar         Beauty      398.71           15
160   ORD38852    Vihaan Aggarwal     clothing     -534.68           25
170   ORD86928        avi iyengar      GROCERY      764.75           15
180   ORD69030    Prisha Dhaliwal        books     1515.65            5
190   ORD78882      David Krishna      GROCERY   ₹1,748.83            5

In [129]:
data = data.set_index("OrderID")

In [132]:
data.head(20)

,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
OrderID,,,,,,,,,,,,,,
ORD51058,CUST04879,Chaitanya Mane,bangalore,Grocery,net_banking,904.48,3.0,10,3.3,2023-04-24,29.0,chaitanya.mane@gmail.com,9454663439,Packaging was bad
ORD70248,CUST00177,Siddharth Sha,DELHI,SPORTS,Net Banking,1823.76,4.0,20,5.0,04-01-2023,38.0,NaN,NaN,great service
ORD43804,CUST04537,Nathaniel Chatterjee,chennai,electronic,Upi,770.67,1.0,0,4.9,11/17/2024,40.0,nathaniel.chatterjee@outlook.com,9573975601,Okayish product
ORD46367,CUST07605,pranit contractor,Jaipur,Clothing,COD,2028.06,1.0,0,2.9,NaN,41.0,pranit.contractor@rediffmail.com,9235766629,NaN
ORD32922,CUST03180,Hemang Chakraborty,Amdavad,FURNITURE,cc,604.00,4.0,10,3.7,14 Jan 2023,44.0,hemang.chakraborty@outlook.com,9731250657,Superb!!! fast delivery
ORD24549,CUST07636,Ishaan Nair,New Delhi,CLOTHING,Debit Card,1271.25,1.0,0,2.8,03/26/2023,32.0,NaN,9755091854,great service
ORD33523,CUST02017,Tara Nagarajan,new delhi,Clothing,credit_card,1349.31,1.0,0,NaN,12-12-2023,34.0,tara.nagarajan@yahoo.com,9759730420,delivery was late
ORD5745,CUST05552,Waida Kapur,Kolkata,Grocery,COD,-1197.45,2.0,5,2.4,11 Dec 2024,43.0,waida.kapur@outlook.com,9141381274,NaN
ORD89157,CUST06968,Turvi Dugar,hyderabad,Grocery,Cash on Delivery,609.16,3.0,0,1.1,03/24/2024,36.0,turvi.dugar@yahoo.com,9635764964,NaN
ORD59831,CUST07512,Kevin Amble,mumbai,BEAUTY,Net Banking,₹876.46,3.0,20,NaN,09/11/2023,69.0,kevin.amble@gmail.com,9810381180,worst product ever received damaged item
ORD93895,CUST07137,ZILMIL PRADHAN,Lucknow,Furnitures,net banking,1605.42,2.0,5,5.0,01/08/2023,29.0,zilmil.pradhan@rediffmail.com,9845870259,Average experience
ORD51587,CUST02047,Udarsh Bala,Jaipur,Clothings,NET BANKING,1910.18,2.0,0,3.7,04/06/2023,38.0,udarsh.bala@rediffmail.com,9306906379,Not satisfied poor quality
ORD100269,CUST00028,Tara Dhar,LUCKNOW,Grocery,NaN,991.07,2.0,5,1.9,08-08-2023,42.0,tara.dhar@gmail.com,9248395775,NaN
ORD58190,CUST05838,Odika Chakrabarti,jaipur,electronics,dc,205.03,2.0,0,NaN,10/21/2024,56.0,odika.chakrabarti@rediffmail.com,NaN,delivery was late
ORD10998,CUST03165,Aarush Seshadri,Bengaluru,Beauty,NET BANKING,Rs.1817.78,1.0,10,3.7,10/18/2024,22.0,aarush.seshadri@gmail.com,9795050042,great service
ORD6606,CUST07862,CHAVVI SHETTY,Jaipur,TOYS,NaN,851.01,1.0,10,4.5,06/06/2023,39.0,NaN,+91-9405672157,Okayish product
ORD27794,CUST03191,Oeshi Bali,Amdavad,sports,Upi,1744.63,1.0,0,4.5,06-04-2024,133.0,oeshi.bali@rediffmail.com,9857479948,Okayish product
ORD20341,CUST01576,Chasmum Ahuja,Calcutta,beauty,cash on delivery,-1277.50,1.0,0,1.8,12-11-2023,37.0,chasmum.ahuja@gmail.com,9611966095,Average experience
ORD13803,CUST05383,Harini Srivastava,MADRAS,grocery,Credit Card,485.45,1.0,0,3.2,11 Oct 2024,26.0,harini.srivastava@hotmail.com,9828047687,value for money
ORD91029,CUST01300,Yauvani Dhar,bengaluru,Clothing,COD,473.96,2.0,25,1.7,12-09-2023,42.0,yauvani.dhar@yahoo.com,9204100769,Not satisfied poor quality

In [135]:
data.loc["ORD51058":"ORD100269", "CustomerID":"Price"]

,CustomerID,CustomerName,City,Category,PaymentMode,Price
OrderID,,,,,,
ORD51058,CUST04879,Chaitanya Mane,bangalore,Grocery,net_banking,904.48
ORD70248,CUST00177,Siddharth Sha,DELHI,SPORTS,Net Banking,1823.76
ORD43804,CUST04537,Nathaniel Chatterjee,chennai,electronic,Upi,770.67
ORD46367,CUST07605,pranit contractor,Jaipur,Clothing,COD,2028.06
ORD32922,CUST03180,Hemang Chakraborty,Amdavad,FURNITURE,cc,604.00
ORD24549,CUST07636,Ishaan Nair,New Delhi,CLOTHING,Debit Card,1271.25
ORD33523,CUST02017,Tara Nagarajan,new delhi,Clothing,credit_card,1349.31
ORD5745,CUST05552,Waida Kapur,Kolkata,Grocery,COD,-1197.45
ORD89157,CUST06968,Turvi Dugar,hyderabad,Grocery,Cash on Delivery,609.16
ORD59831,CUST07512,Kevin Amble,mumbai,BEAUTY,Net Banking,₹876.46
ORD93895,CUST07137,ZILMIL PRADHAN,Lucknow,Furnitures,net banking,1605.42
ORD51587,CUST02047,Udarsh Bala,Jaipur,Clothings,NET BANKING,1910.18
ORD100269,CUST00028,Tara Dhar,LUCKNOW,Grocery,NaN,991.07

In [138]:
data.iloc[0:13, 0:6]

,CustomerID,CustomerName,City,Category,PaymentMode,Price
OrderID,,,,,,
ORD51058,CUST04879,Chaitanya Mane,bangalore,Grocery,net_banking,904.48
ORD70248,CUST00177,Siddharth Sha,DELHI,SPORTS,Net Banking,1823.76
ORD43804,CUST04537,Nathaniel Chatterjee,chennai,electronic,Upi,770.67
ORD46367,CUST07605,pranit contractor,Jaipur,Clothing,COD,2028.06
ORD32922,CUST03180,Hemang Chakraborty,Amdavad,FURNITURE,cc,604.00
ORD24549,CUST07636,Ishaan Nair,New Delhi,CLOTHING,Debit Card,1271.25
ORD33523,CUST02017,Tara Nagarajan,new delhi,Clothing,credit_card,1349.31
ORD5745,CUST05552,Waida Kapur,Kolkata,Grocery,COD,-1197.45
ORD89157,CUST06968,Turvi Dugar,hyderabad,Grocery,Cash on Delivery,609.16
ORD59831,CUST07512,Kevin Amble,mumbai,BEAUTY,Net Banking,₹876.46
ORD93895,CUST07137,ZILMIL PRADHAN,Lucknow,Furnitures,net banking,1605.42
ORD51587,CUST02047,Udarsh Bala,Jaipur,Clothings,NET BANKING,1910.18
ORD100269,CUST00028,Tara Dhar,LUCKNOW,Grocery,NaN,991.07

In [141]:
data[data["Quantity"] > 2]

,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
OrderID,,,,,,,,,,,,,,
ORD51058,CUST04879,Chaitanya Mane,bangalore,Grocery,net_banking,904.48,3.0,10,3.3,2023-04-24,29.0,chaitanya.mane@gmail.com,9454663439,Packaging was bad
ORD70248,CUST00177,Siddharth Sha,DELHI,SPORTS,Net Banking,1823.76,4.0,20,5.0,04-01-2023,38.0,NaN,NaN,great service
ORD32922,CUST03180,Hemang Chakraborty,Amdavad,FURNITURE,cc,604.00,4.0,10,3.7,14 Jan 2023,44.0,hemang.chakraborty@outlook.com,9731250657,Superb!!! fast delivery
ORD89157,CUST06968,Turvi Dugar,hyderabad,Grocery,Cash on Delivery,609.16,3.0,0,1.1,03/24/2024,36.0,turvi.dugar@yahoo.com,9635764964,NaN
ORD59831,CUST07512,Kevin Amble,mumbai,BEAUTY,Net Banking,₹876.46,3.0,20,NaN,09/11/2023,69.0,kevin.amble@gmail.com,9810381180,worst product ever received damaged item
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ORD65935,CUST05320,Madhavi Raj,Poona,books,UPI,692.12,4.0,20,4.9,22/01/2024,45.0,madhavi.raj@gmail.com,9427416720,NaN
ORD68829,CUST01971,AARAV BOBAL,Bombay,Beauty,CREDIT CARD,-2040.44,4.0,15,3.9,2023-03-19,45.0,NaN,+91-9795734459,great service
ORD51858,CUST01818,Gaurang Korpal,poona,Furniture,Upi,977.41,4.0,0,NaN,2024-11-27,28.0,gaurang.korpal@gmail.com,+91-9735065800,delivery was late
ORD92081,CUST02778,Jalsa Rastogi,calcutta,electronic,net banking,"₹1,854.93",4.0,0,2.8,04/08/2024,34.0,jalsa.rastogi@outlook.com,9486328773,Product as described
ORD49057,CUST01636,MAX OM,chennai,FURNITURE,debit card,Rs.1961.37,4.0,0,5.0,2023-06-11,32.0,max.om@outlook.com,9123457578,Amazing quality!!!

In [143]:
data[data["Category"]=="SPORTS"]

,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
OrderID,,,,,,,,,,,,,,
ORD70248,CUST00177,Siddharth Sha,DELHI,SPORTS,Net Banking,1823.76,4.0,20,5.0,04-01-2023,38.0,NaN,NaN,great service
ORD12449,CUST08424,Manthan Agate,amdavad,SPORTS,dc,1338.21,3.0,20,3.0,09 May 2024,139.0,manthan.agate@hotmail.com,NaN,delivery was late
ORD67238,CUST02449,Arjun Wable,Bangalore,SPORTS,Upi,1077.90,1.0,0,0.5,11/23/2023,27.0,arjun.wable@outlook.com,9245225726,Superb!!! fast delivery
ORD42629,CUST02949,FITAN SANGHVI,CHENNAI,SPORTS,Upi,1745.92,1.0,0,3.5,2024-09-19,35.0,fitan.sanghvi@hotmail.com,9753156441,value for money
ORD9299,CUST05402,Arjun Walia,Madras,SPORTS,Upi,Rs.756.74,-3.0,5,3.4,07/02/2023,32.0,arjun.walia@outlook.com,9123457998,Okayish product
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ORD13566,CUST00910,Arunima Chacko,Jaipur,SPORTS,CREDIT CARD,1834.13,2.0,0,3.0,03 Nov 2024,105.0,arunima.chacko@outlook.com,9103812175,delivery was late
ORD97185,CUST02366,Janaki Dugar,Poona,SPORTS,Upi,642.90,2.0,25,1.7,04/12/2024,57.0,janaki.dugar@yahoo.com,9310566329,Superb!!! fast delivery
ORD73553,CUST02637,Vanya Biswas,MADRAS,SPORTS,UPI,-394.37,5.0,0,1.6,02-10-2024,40.0,vanya.biswas@hotmail.com,9126325976,Product as described
ORD69247,CUST01237,Kevin Gokhale,Lucknow,SPORTS,Cash on Delivery,2721.42,2.0,0,2.4,20/02/2023,59.0,kevin.gokhale@rediffmail.com,9649407241,NaN
ORD65094,CUST07897,ATHARV LAD,AHMEDABAD,SPORTS,net_banking,₹314.85,-1.0,0,2.9,27/07/2023,55.0,atharv.lad@rediffmail.com,9492960060,Amazing quality!!!

In [151]:
data[(data["Quantity"] > 2) & (data["Category"]=="SPORTS")]

,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
OrderID,,,,,,,,,,,,,,
ORD70248,CUST00177,Siddharth Sha,DELHI,SPORTS,Net Banking,1823.76,4.0,20,5.0,04-01-2023,38.0,NaN,NaN,great service
ORD12449,CUST08424,Manthan Agate,amdavad,SPORTS,dc,1338.21,3.0,20,3.0,09 May 2024,139.0,manthan.agate@hotmail.com,NaN,delivery was late
ORD44396,CUST08428,Lila Virk,delhi,SPORTS,NaN,1397.94,3.0,0,4.3,02 Oct 2023,26.0,lila.virk@gmail.com,9234028867,Good product loved it
ORD59357,CUST08213,Gabriel Modi,Calcutta,SPORTS,credit_card,738.21,3.0,25,2.7,2023-12-21,27.0,gabriel.modi@outlook.com,9413309813,Product as described
ORD99935,CUST07276,PRIYA CHAUDRY,mumbai,SPORTS,upi,969.07,3.0,10,2.4,2024-06-11,28.0,priya.chaudry@hotmail.com,9384531913,Good product loved it
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ORD91508,CUST07847,Omisha Sahni,Mumbai,SPORTS,Credit Card,1687.75,4.0,15,3.8,01/09/2023,26.0,omisha.sahni@rediffmail.com,9237438486,Good product loved it
ORD49565,CUST06398,SAI MISRA,lucknow,SPORTS,CC,1451.97,4.0,25,5.0,01-12-2023,21.0,sai.misra@hotmail.com,9759544072,Packaging was bad
ORD75975,CUST05875,Daniel Anne,Bombay,SPORTS,Upi,881.18,3.0,5,2.8,03-06-2023,54.0,daniel.anne@outlook.com,9480746667,Good product loved it
ORD98701,CUST02428,Qadim Suresh,Bangalore,SPORTS,DC,₹148.91,3.0,25,2.1,12/03/2024,37.0,qadim.suresh@outlook.com,9841474005,Packaging was bad
ORD73553,CUST02637,Vanya Biswas,MADRAS,SPORTS,UPI,-394.37,5.0,0,1.6,02-10-2024,40.0,vanya.biswas@hotmail.com,9126325976,Product as described

In [155]:
data.groupby("City")["Quantity"].sum()

City
 Delhi        2931.0
 Hyderabad    5422.0
 Lucknow      5310.0
 Mumbai       2779.0
AHMEDABAD     4026.0
Ahmedabad     4414.0
Amdavad       4380.0
BANGALORE     3054.0
BOMBAY        2868.0
Bangalore     3107.0
Banglore      2976.0
Bengaluru     3086.0
Bombay        2638.0
CALCUTTA      3753.0
CHENNAI       3546.0
Calcutta      3687.0
Chennai       3763.0
DELHI         3015.0
Delhi         3051.0
HYDERABAD     5309.0
Hyderabad     5404.0
JAIPUR        5613.0
Jaipur        5511.0
Jaipur        5286.0
KOLKATA       3597.0
Kolkata       3606.0
LUCKNOW       5389.0
Lucknow       5167.0
MADRAS        3478.0
MUMBAI        2716.0
Madras        3675.0
Mumbai        2772.0
NEW DELHI     3249.0
New Delhi     3161.0
PUNE          4172.0
Poona         4361.0
Pune          4344.0
ahmedabad     4358.0
amdavad       4332.0
bangalore     3200.0
banglore      3232.0
bengaluru     2999.0
bombay        2715.0
calcutta      3457.0
chennai       3776.0
delhi         2931.0
hyderabad     5550.0
jaipur        5225.0
kolkata       3633.0
lucknow       5237.0
madras        3793.0
mumbai        2750.0
mumbai        2800.0
new delhi     3043.0
poona         4097.0
pune          4336.0
Name: Quantity, dtype: float64

In [157]:
data["Category"].unique()

<StringArray>
[    'Grocery',      'SPORTS',  'electronic',    'Clothing',   'FURNITURE',
    'CLOTHING',      'BEAUTY',  'Furnitures',   'Clothings', 'electronics',
      'Beauty',        'TOYS',      'sports',      'beauty',     'grocery',
        'Book',      'Sports',   'Groceries', 'Electronics',        'book',
       'Books',     'GROCERY',   'Clothing ',       'books',   'furniture',
 'ELECTRONICS',   'Furniture',    'clothing',        'Toys',  'Electronic',
        'toys',         'Toy',       'BOOKS',         'toy',       'Sport']
Length: 35, dtype: str

In [160]:
data["Category"] = data["Category"].str.strip().str.lower().str.rstrip("s").str.replace('grocerie', "grocery")

In [161]:
data["Category"].unique()

<StringArray>
[   'grocery',      'sport', 'electronic',   'clothing',  'furniture',
     'beauty',        'toy',       'book']
Length: 8, dtype: str